### ISSUE TITLE
Use amount as another dimension

### ISSUE THREAD

**Issue by tarioch** [beancount/smart_importer#22]
I think it would make sense to also include the amount as a dimension as most of the time, the same entries should also have a similar amount.

**Comment by johannesjh** [comment]
I guess we would need some kind of fuzzy matching here; the rough order of magnitude of amounts should be the same. We could log-transform the amounts, but we would still need some kind of fuzziness in the classifier. Any idea how this can be implemented in scikit-learn? Fuzzy SVMs exist, but fuzziness does not seem to be their default behavior, right? Eg. see https://www.researchgate.net/post/How_are_fuzzy_SVM_different_from_simple_SVM

**Comment by mondjef** [comment]
I second this, to give a real world use case of how this can influence the ML to be more precise here is an example of my own behaviours.  I shop normally at a particular grocery store to get my groceries, however this grocery store also sells beer and wine and I like to track my groceries and alcohol expenses separately.  Most likely if I am spending $25 or less it would more than likely be for beer or wine rather than grocery shopping for the week which would be well over $100.  
This also raises the usefulness of another dimension...day of week or time of day.  I can assure you that if I spend $30 on a Friday night it is most likely for beer or wine compared to if I spend $30 on a Sat morning where its more than likely for grocery items that ran out during the week.
For $ amounts (or any other continuous variable) depending on the model you either bin it or scale/normalize it.  I think SVMs don't need binning but it should be scaled or normalized somehow.
