### ISSUE TITLE
predict tags/metadata/links

### ISSUE THREAD

**Issue by zacchiro** [beancount/smart_importer#34]
I'm loving smart_importer, but it left me with the desire of also being able to predict tags/metadata/links.
I understand the model will be more complex/larger, but it should be doable, right?. Have you already considered the idea?
Either way, thanks a bunch for smart_importer!

**Comment by johannesjh** [comment]
Not sure how to proceed with this request: 

* The straightforward way of adding more classifiers is of course possible, but does not scale well in the current implementation: We currently train a separate classifier for each desired output (for a good reason *see below). One could of course add an additional classifier for each additional attribute to be predicted, such as tags, metadata, links etc... but this would increase code duplication and it would come with a performance penalty since machine learning models are trained separately for each classifier.

* Alternatively and in a less straightforward way, the machine learning problem could be framed differently. E.g., as discussed with @tbm in #37, to predict entire output structures consisting of postings, metadata, links, events etc. 

\* good reason:  
 One classifier is trained to predict payees and another classifier is trained to predict postings. The reason why they are trained separately is as follows: The `PredictPostings` classifier is trained with tuples of <transaction, posting>, in order to be able to learn from transactions with many postings. But for the `PredictPayees` classifier, it is sufficient to train with transaction objects.

**Comment by zacchiro** [comment]
On Sun, Apr 29, 2018 at 09:47:21PM +0000, johannesjh wrote:
> * Alternatively and in a less straightforward way, the machine
>   learning problem could be framed differently. E.g., as discussed
>   with @tbm in #37, to predict entire output structures consisting of
>   postings, metadata, links, events etc.

That might be a viable alternative, although I've no idea whether it'd
work better or worse than the current approach.

In the current approach, though, modularity is a nice feature. So for
this one I was indeed thinking at an additional classifier, and that
it'd use as training input the same information currently used for
training the payee/account classifiers.

If anything, what I find currently *not* very modular is the decorator
interface. In some cases having the ability to explicitly call the
training function and the prediction function(s) by hand in importers
would be nice. (Sure, you can do it now with some effort, but as those
are not advertised as the recommended entry points, people won't do that
I think.)

**Comment by johannesjh** [comment]
Update @zacchiro: I refactored the decorator code. It is now much more modular, see Pull Request #49 and corresponding ticket #47.

**Comment by zacchiro** [comment]
@johannesjh looks good to me, thanks!

**Comment by johannesjh** [comment]
Update to this ticket: In the meantime, @yagebu did a major refactoring (see ticket #47, pull request #62). This removed a lot of code duplication and reduced the overall code size. More importantly for this ticket, creating custom pipelines that predict other targets is now much more elegant and simple. For example, have a look at how PredictPayees and PredictPostings is now implemented by overwriting.

I think this ticket can be closed, right?
