### ISSUE TITLE
Refactor common part of predict_payees and predict_postings

### ISSUE THREAD

**Issue by tarioch** [beancount/smart_importer#47]
I think it would make it cleaner and easier to expand if we refactor the common part into an own class. 
That way each could simply focus on their respective parts.

Parts I see:
* [Common] dealing with it being a decorator
* [Common] loading training data
* [Specific] training a model
* [Common] getting a list of imported transactions
* [Specific] enhancing the transactions
* [Common] merge the enhanced transactions with the rest of imported entries

What do you think? @johannesjh

**Comment by johannesjh** [comment]
yes, I agree. Maybe an abstract class `SmartImporterDecorator`?

Note: This is quite similar to what is needed for #45, i.e., to split the code into multiple methods that can be overwritten by users by subclassing the decorators, e.g., in order to add an additional input to the machine learning pipeline.

**Comment by tarioch** [comment]
Yes that's exactly what I think.
It should also help with #34

**Comment by johannesjh** [comment]
I'll give the refactoring a try, i hope I'll find enough time this weekend.

**Comment by johannesjh** [comment]
work in progress in branch `feature/refs-47-refactoring`
